/**
 * 该文件由小讯鸽插件自动生成!
 * 请不要手动修改
 */
export default class ResList implements Core.ICoreResList {

	public preloadControl: { [key: string]: { isLoad: boolean, path: string } } = {
		BindSuccessView: { isLoad: false, path:'Prefab/view/BindSuccessView' },
		BindingGiftView: { isLoad: false, path:'Prefab/view/BindingGiftView' },
		CatchGold_CatchGoldMainView: { isLoad: false, path:'Prefab/view/CatchGold/CatchGoldMainView' },
		DailyTaskView: { isLoad: false, path:'Prefab/view/DailyTaskView' },
		DividendView: { isLoad: false, path:'Prefab/view/DividendView' },
		FeedbackView: { isLoad: false, path:'Prefab/view/FeedbackView' },
		FunGameView: { isLoad: false, path:'Prefab/view/FunGameView' },
		GuideBookView: { isLoad: false, path:'Prefab/view/GuideBookView' },
		IncomeHintView: { isLoad: false, path:'Prefab/view/IncomeHintView' },
		InvitationListView: { isLoad: false, path:'Prefab/view/InvitationListView' },
		InvitationView: { isLoad: false, path:'Prefab/view/InvitationView' },
		LoginView: { isLoad: true, path:'Prefab/view/LoginView' },
		MainView: { isLoad: true, path:'Prefab/view/MainView' },
		PrivacyView: { isLoad: false, path:'Prefab/view/PrivacyView' },
		PromptView: { isLoad: true, path:'Prefab/view/PromptView' },
		RankView: { isLoad: false, path:'Prefab/view/RankView' },
		RecruitStallOwnerView: { isLoad: false, path:'Prefab/view/RecruitStallOwnerView' },
		RewardView: { isLoad: false, path:'Prefab/view/RewardView' },
		SettingView: { isLoad: false, path:'Prefab/view/SettingView' },
		ShareView: { isLoad: false, path:'Prefab/view/ShareView' },
		SignInView: { isLoad: false, path:'Prefab/view/SignInView' },
		StallInfoView: { isLoad: false, path:'Prefab/view/StallInfoView' },
		SupremeInfoView: { isLoad: false, path:'Prefab/view/SupremeInfoView' },
		SysPopupView: { isLoad: true, path:'Prefab/view/SysPopupView' },
		TurntableAddressView: { isLoad: false, path:'Prefab/view/TurntableAddressView' },
		TurntableHistoryView: { isLoad: false, path:'Prefab/view/TurntableHistoryView' },
		TurntableRuleView: { isLoad: false, path:'Prefab/view/TurntableRuleView' },
		TurntableView: { isLoad: false, path:'Prefab/view/TurntableView' },
		UserProtocolView: { isLoad: false, path:'Prefab/view/UserProtocolView' },
		WithdrawDetailView: { isLoad: false, path:'Prefab/view/WithdrawDetailView' },
		WithdrawRecordView: { isLoad: false, path:'Prefab/view/WithdrawRecordView' },
		WithdrawView: { isLoad: false, path:'Prefab/view/WithdrawView' },
	};

	public initList: string[] = [
		'Atlas_mainUIAtlas',
		'Atlas_stallSceneAtlas',
		'Mp3_onclick',
		'Texture_common2',
		'Texture_common4',
	];

	public viewMap: { [key: string]: string[] } = {
		BindSuccessView: [
		],
		BindingGiftView: [
		],
		CatchGold_CatchGoldMainView: [
		],
		DailyTaskView: [
		],
		DividendView: [
		],
		FeedbackView: [
		],
		FunGameView: [
		],
		GuideBookView: [
		],
		IncomeHintView: [
		],
		InvitationListView: [
		],
		InvitationView: [
		],
		LoginView: [
		],
		MainView: [
		],
		PrivacyView: [
		],
		PromptView: [
		],
		RankView: [
		],
		RecruitStallOwnerView: [
		],
		RewardView: [
		],
		SettingView: [
		],
		ShareView: [
		],
		SignInView: [
		],
		StallInfoView: [
		],
		SupremeInfoView: [
		],
		SysPopupView: [
		],
		TurntableAddressView: [
		],
		TurntableHistoryView: [
		],
		TurntableRuleView: [
		],
		TurntableView: [
		],
		UserProtocolView: [
		],
		WithdrawDetailView: [
		],
		WithdrawRecordView: [
		],
		WithdrawView: [
		],
	};

	public resMap: { [key: string]: { type: number; path: string } } = {
		Atlas_catchGoldAtlas: { type: Core.StaticConfig.RES_TYPE_ATLAS, path: 'Atlas/catchGoldAtlas' },
		Atlas_luckyAtlas: { type: Core.StaticConfig.RES_TYPE_ATLAS, path: 'Atlas/luckyAtlas' },
		Atlas_mainUIAtlas: { type: Core.StaticConfig.RES_TYPE_ATLAS, path: 'Atlas/mainUIAtlas' },
		Atlas_stallSceneAtlas: { type: Core.StaticConfig.RES_TYPE_ATLAS, path: 'Atlas/stallSceneAtlas' },
		Config_config: { type: Core.StaticConfig.RES_TYPE_JSON, path: 'Config/config' },
		Mp3_building: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/building' },
		Mp3_calling: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/calling' },
		Mp3_cashier: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/cashier' },
		Mp3_catchGold_getbonus: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/catchGold/getbonus' },
		Mp3_catchGold_gethammer: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/catchGold/gethammer' },
		Mp3_catchGold_music: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/catchGold/music' },
		Mp3_collectcoin: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/collectcoin' },
		Mp3_getbalance: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/getbalance' },
		Mp3_getcoin: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/getcoin' },
		Mp3_godappear: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/godappear' },
		Mp3_godleave: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/godleave' },
		Mp3_levelup: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/levelup' },
		Mp3_lobby: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/lobby' },
		Mp3_menuclose: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/menuclose' },
		Mp3_onclick: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/onclick' },
		Mp3_slot: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/slot' },
		Mp3_slotbonus: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/slotbonus' },
		Mp3_slotfinish: { type: Core.StaticConfig.RES_TYPE_MP3, path: 'Mp3/slotfinish' },
		Prefab_component_GoldIcon: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/GoldIcon' },
		Prefab_component_InviteInfoItem: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/InviteInfoItem' },
		Prefab_component_ItemBox: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/ItemBox' },
		Prefab_component_ListViewComponent: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/ListViewComponent' },
		Prefab_component_MenuBtn: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/MenuBtn' },
		Prefab_component_RankItem: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/RankItem' },
		Prefab_component_StallItem: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/StallItem' },
		Prefab_component_TurntableHistoryItem: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/TurntableHistoryItem' },
		Prefab_component_WithdrawDetailListItem: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/WithdrawDetailListItem' },
		Prefab_component_WithdrawRecordListItem: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/component/WithdrawRecordListItem' },
		Prefab_view_CatchGold_CatchGoldItem: { type: Core.StaticConfig.RES_TYPE_PREFAB, path: 'Prefab/view/CatchGold/CatchGoldItem' },
		Spine_Djjl: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/Djjl/Djjl' },
		Spine_LQHB: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/LQHB/LQHB' },
		Spine_YQYL: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/YQYL/YQYL' },
		Spine_ZBJL_aixin: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/ZBJL-aixin/ZBJL-aixin' },
		Spine_ZBJL_shoujiBG: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/ZBJL-shoujiBG/ZBJL-shoujiBG' },
		Spine_ZBJL_shoujiSG: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/ZBJL-shoujiSG/ZBJL-shoujiSG' },
		Spine_baiditan_01: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_01/baiditan_01' },
		Spine_baiditan_02: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_02/baiditan_02' },
		Spine_baiditan_03: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_03/baiditan_03' },
		Spine_baiditan_04: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_04/baiditan_04' },
		Spine_baiditan_05: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_05/baiditan_05' },
		Spine_baiditan_06: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_06/baiditan_06' },
		Spine_baiditan_07: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_07/baiditan_07' },
		Spine_baiditan_08: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_08/baiditan_08' },
		Spine_baiditan_09: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_09/baiditan_09' },
		Spine_baiditan_10: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/baiditan_10/baiditan_10' },
		Spine_bangding: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/bangding/bangding' },
		Spine_bdyl: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/bdyl/bdyl' },
		Spine_catchGold_count_1: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/catchGold/count_1/jinbi' },
		Spine_catchGold_count_2: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/catchGold/count_2/jiantou' },
		Spine_catchGold_count_3: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/catchGold/count_3/chibang' },
		Spine_catchGold_player: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/catchGold/player/jiejinbi' },
		Spine_catchGold_ready: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/catchGold/ready/zhunbei' },
		Spine_chibang: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/chibang/chibang' },
		Spine_dianji: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/dianji/dianji' },
		Spine_guang1: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/guang1/guang1' },
		Spine_guang2: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/guang2/guang2' },
		Spine_guangquan: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/guangquan/guangquan' },
		Spine_hongbaocaidai: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/hongbaocaidai/hongbaocaidai' },
		Spine_jiantou: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/jiantou/jiantou' },
		Spine_jiasu: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/jiasu/jiasu' },
		Spine_jiejinbi: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/jiejinbi/jiejinbi' },
		Spine_jinbi: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/jinbi/jinbi' },
		Spine_js: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/js/js' },
		Spine_jzjd: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/jzjd/jzjd' },
		Spine_lingqujinbi: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/lingqujinbi/lingqujinbi' },
		Spine_sjtw: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/sjtw/sjtw' },
		Spine_tuijian: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/tuijian/tuijian' },
		Spine_tztj1: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/tztj1/tztj1' },
		Spine_tztj2: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/tztj2/tztj2' },
		Spine_tztj3: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/tztj3/tztj3' },
		Spine_xs: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/xs/xs' },
		Spine_xslb: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/xslb/xslb' },
		Spine_yilinqu: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/yilinqu/yilinqu' },
		Spine_zhuangxiu: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/zhuangxiu/zhuangxiu' },
		Spine_zhuangxiu2: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/zhuangxiu2/zhuangxiu2' },
		Spine_zmtz01: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/zmtz01/zmtz01' },
		Spine_zmtz02: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/zmtz02/zmtz02' },
		Spine_zmtz03: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/zmtz03/zmtz03' },
		Spine_zztz1: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/zztz1/zztz1' },
		Spine_zztz2: { type: Core.StaticConfig.RES_TYPE_SPINE, path: 'Spine/zztz2/zztz2' },
		Texture_CatchGold_qwyx002: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/CatchGold/qwyx002' },
		Texture_CatchGold_yx000: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/CatchGold/yx000' },
		Texture_CatchGold_yx007: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/CatchGold/yx007' },
		Texture_CatchGold_yx012: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/CatchGold/yx012' },
		Texture_common2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/common2' },
		Texture_common4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/common4' },
		Texture_dl_bg: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/dl_bg' },
		Texture_fhxq002: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/fhxq002' },
		Texture_fhxq003: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/fhxq003' },
		Texture_load: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/load' },
		Texture_main_stall_1_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_1/1' },
		Texture_main_stall_1_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_1/2' },
		Texture_main_stall_1_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_1/3' },
		Texture_main_stall_1_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_1/4' },
		Texture_main_stall_1_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_1/5' },
		Texture_main_stall_10_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_10/1' },
		Texture_main_stall_10_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_10/2' },
		Texture_main_stall_10_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_10/3' },
		Texture_main_stall_10_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_10/4' },
		Texture_main_stall_10_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_10/5' },
		Texture_main_stall_2_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_2/1' },
		Texture_main_stall_2_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_2/2' },
		Texture_main_stall_2_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_2/3' },
		Texture_main_stall_2_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_2/4' },
		Texture_main_stall_2_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_2/5' },
		Texture_main_stall_3_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_3/1' },
		Texture_main_stall_3_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_3/2' },
		Texture_main_stall_3_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_3/3' },
		Texture_main_stall_3_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_3/4' },
		Texture_main_stall_3_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_3/5' },
		Texture_main_stall_4_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_4/1' },
		Texture_main_stall_4_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_4/2' },
		Texture_main_stall_4_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_4/3' },
		Texture_main_stall_4_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_4/4' },
		Texture_main_stall_4_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_4/5' },
		Texture_main_stall_5_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_5/1' },
		Texture_main_stall_5_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_5/2' },
		Texture_main_stall_5_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_5/3' },
		Texture_main_stall_5_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_5/4' },
		Texture_main_stall_5_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_5/5' },
		Texture_main_stall_6_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_6/1' },
		Texture_main_stall_6_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_6/2' },
		Texture_main_stall_6_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_6/3' },
		Texture_main_stall_6_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_6/4' },
		Texture_main_stall_6_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_6/5' },
		Texture_main_stall_7_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_7/1' },
		Texture_main_stall_7_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_7/2' },
		Texture_main_stall_7_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_7/3' },
		Texture_main_stall_7_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_7/4' },
		Texture_main_stall_7_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_7/5' },
		Texture_main_stall_8_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_8/1' },
		Texture_main_stall_8_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_8/2' },
		Texture_main_stall_8_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_8/3' },
		Texture_main_stall_8_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_8/4' },
		Texture_main_stall_8_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_8/5' },
		Texture_main_stall_9_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_9/1' },
		Texture_main_stall_9_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_9/2' },
		Texture_main_stall_9_3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_9/3' },
		Texture_main_stall_9_4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_9/4' },
		Texture_main_stall_9_5: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/main/stall_9/5' },
		Texture_mrrw2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/mrrw2' },
		Texture_phb: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/phb' },
		Texture_phb002: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/phb002' },
		Texture_phb011: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/phb011' },
		Texture_share_yafxy1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/share/yafxy1' },
		Texture_share_yafxy1_1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/share/yafxy1_1' },
		Texture_share_yafxy1_2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/share/yafxy1_2' },
		Texture_share_yafxy2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/share/yafxy2' },
		Texture_share_yafxy3: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/share/yafxy3' },
		Texture_share_yafxy4: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/share/yafxy4' },
		Texture_sz6: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/sz6' },
		Texture_tx11: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/tx11' },
		Texture_tx_bg: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/tx_bg' },
		Texture_xslb2: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/xslb2' },
		Texture_zjm36: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/zjm36' },
		Texture_zjm40: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/zjm40' },
		Texture_zjm_bg: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/zjm_bg' },
		Texture_zjm_bg1: { type: Core.StaticConfig.RES_TYPE_SPRITE_FRAME, path: 'Texture/zjm_bg1' },
	};

}